apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: passport-reader
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: passport-reader
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
